// <auto-generated />
namespace eCommerce.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class contactmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contactmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201912042206298_contactmigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
